### ISSUE TITLE
107000 应该为 壹拾万零柒仟 还是壹拾万柒仟

### ISSUE THREAD

**Issue by han8435762** [cnwhy/nzh#12]
107000 应该为 
壹拾万零柒仟
壹拾万柒仟
我在各方查证 都说第一种是错误的 
我使用nzh转换完毕是第一种
然后我试着从配置方面入手 搞成第二种 发现搞不定 是不是必须改源码了

**Comment by cnwhy** [comment]
貌似大家都是用的第二种, 我在搞清楚规则后, 尽快改正    感谢你的反馈

**Comment by han8435762** [comment]
ok 感谢~

**Comment by cnwhy** [comment]
暂时修改转换规则如下:
```
"100100" > "一十万零一百"
"101000" > "一十万一千"
"1010001000" > "一十亿一千万一千"
"1000001000" > "一十亿零一千"
```

参考资料:
[繁读法](https://baike.baidu.com/item/%E7%B9%81%E8%AF%BB%E6%B3%95)
[中文数字](https://baike.baidu.com/item/%E7%B9%81%E8%AF%BB%E6%B3%95)

`1000001000` 应转为 `一十亿零一千` 还是 `一十亿一千` 资料没有明确.  
其它工具转换的结果, 两者都有.

@han8435762 以上修改已发布在1.0.4版本中 可以升级试试
