### ISSUE TITLE
随手一试，1.00，输出“壹元”，“整”字没了。

### ISSUE THREAD

**Issue by petesun** [cnwhy/nzh#20]
`nzhcn.toMoney("1.00", { outSymbol: false }); //壹元`
我随手一试，就发现问了。“整”字没了，明显不合规范，希望修改。
购物显示金额，都是2位小数，是十分普遍的应用场景。

**Comment by cnwhy** [comment]
这里转换规则参照了数学中小数位的规则。
数学中 `1.00` 不一定是一元整 而是保留两位小数位后的写法，原值可能是 `1.001` , `1.002`，所以特意没有加`整`；
如果需要绕开这一规则，可以先转为 `number` 再转换

**Comment by petesun** [comment]
感谢作者的回复。
但我依然坚持认为是问题，希望作者修改。理由有如下3点：

1.使用您功能的，很可能是电商、超市、企业、工厂，货物清单，收银结算等。 用数学里的规则，明显对实际使用场景不友好。

2.nzhcn.toMoney(101100.10", { outSymbol: false });  输出“壹拾万壹仟壹佰元壹角”，阿拉伯数字中有零，但输出中没有“零”。
   nzhcn.toMoney(101101.00", { outSymbol: false });  输出"壹拾万壹仟壹佰零壹元"，阿拉伯数字中有零，输出中也有“零”。
   我认为，您的功能，遵循的是”人民银行人民币大小写转换规定”。如果数学上有这用的规定，那是我孤陋寡闻了。

3.假设您的功能就是为了您口中所说的“数学”规则，那您是否应警告使用者，这是数学规则，并不符合”人民银行人民币大小写转换规定”，请谨慎使用。避免像我一样，希望使用”人民币大小写转换规定”，结果和期望不符，出现问题。

**Comment by cnwhy** [comment]
> 中文大写金额数字到"元"为止的，在"元"之后，应写"整"（或"正"）字，在"角"之后，可以不写"整"（或"正"）字。大写金额数字有"分"的，"分"后面不写"整"（或"正"）字。

首先 `1` 和 `1.00` 的区别是一个常识问题，即便没有按用户预期输出整字，用户也能理解其原因，转数字类型即可解决问题, 反之不好解决；
其次，在使用场景上, 更多可能是 数字类型转金额，那么就不存在 1 和 1.00 的冲突；
如果按你对这句话的理解，就算个用户 传一个1.001进去，也必须输出整字因为没有角也没有分

**Comment by petesun** [comment]
1. 我认为，您的功能，如果遵循的是”人民银行人民币大小写转换规定”，那么请彻底遵循，而不是有的遵循，有的不遵循。
如果您觉得，有超出”人民银行人民币大小写转换规定”的部分，请报错。

2. 如果您的功能，不遵循”人民银行人民币大小写转换规定”，也请明确告诉使用者。避免像我一样，希望使用”人民币大小写转换规定”，结果和期望不符，出现问题。而不是假设，使用者都100%，理解您说的“常识”。
在您眼中，`1.00`输出“壹元”是常识。在我眼里，`1.00`输出“壹元整”是常识。我相信，也存在很多人的常识，和我是一样的。

**Comment by cnwhy** [comment]
每个人理解可能不一样, 先抛开 `1.00` 这里的争议, 还有哪些规定没符合, 能否把细则贴上来;

**Comment by petesun** [comment]
1. 首先真心实意的感谢作者，也希望作者的项目越来越好，所以我才坚持作者修改问题。

2. 我把作者功能输出结果的所有情况，进行排查比对，发现除了`1.00`问题之外，都符合规范。

多说几句：
本人在金融领域，某投行工作5年。现在在税务领域，做‘国家税务总局’中标项目。
咱们国家纸质发票上面大写金额的功能是我写的。
自己完全写的出来`JavaScript`版本，N年前就写了`C++`版本，运行效率自不用说，语言优势明显。
突然想起来逛逛GitHub，就是想学习瞻仰一下大神的代码。

**Comment by cnwhy** [comment]
你的意思, 就是只要是以元结尾的情况 就必须以加上整;  
https://github.com/cnwhy/nzh/blob/cade92b8902bafb55ede776fe73ce6218cbf5a32/test/testData.js#L126-L142

我也参考过一些其它 的转换工具, 有的不加, 有的加;

**Comment by petesun** [comment]
> 中文大写金额数字到"元"为止的，在"元"之后，应写"整"（或"正"）字，在"角"之后，可以不写"整"（或"正"）字。大写金额数字有"分"的，"分"后面不写"整"（或"正"）字。

是的，您自己在上面的评论中，也引用了规范。

> 在"元"之后，应写"整"（或"正"）字

我觉得，您也可以加参数，来实现不同功能，只要保证至少有一种规范的能用就行。
我觉得约定兼容处理是好的选择，报错应该就不用了。

**Comment by petesun** [comment]
举个栗子，在税务使用场景中，“字符串类型”比“数字类型”使用的多。
量最大的发票查询，大部分红字发票，是“字符串类型”。
相比之下量小的蓝字发票，需要计算，才用到“数字类型”。

**Comment by petesun** [comment]
想了想，还是不给作者添麻烦了。

**Comment by cnwhy** [comment]
这几天有点忙。之后会加上一个配置，来处理这个整字的分歧。

**Comment by petesun** [comment]
真心感谢作者，给个赞。
