### ISSUE TITLE
“读数法”分级写零问题

### ISSUE THREAD

**Issue by petesun** [cnwhy/nzh#23]
又来打扰作者了。^_^
本来，不想说这个问题的。既然有人提了[108080 壹拾万 后边应不应该加 零 ?](https://github.com/cnwhy/nzh/issues/22)，那我也说几句。

输入`108080`
输出`壹拾万捌仟零捌拾元整`
这里没毛病，使用[读数法](https://baike.baidu.com/item/%E8%AF%BB%E6%95%B0%E6%B3%95/22670728?fr=aladdin)，不写零。

> 3、一个数末尾有0，不论有几个都可不读，分级后任一级末尾有零，也可不读，在需要读出时，不论有几个0，均只读一个零，中间有0的，也不论连续有几个0，需要读出时只读一个零

输入`11000001000`
输出`壹佰壹拾亿零壹仟元整`
这里就写零了。

建议作者，要么都写零，要么都不写零，要么用参数作为开关，自行控制。

我自己的实现，是不写零，输出`壹佰壹拾亿壹仟元整`。逛了下GitHub，例如[Format-RMB](https://github.com/bazingaedward/ChinaCurrency)，也是不写零。

这里关键点，就是涉及到了万位全零的处理，除此之外的情况，作者都是不写零的，都没啥问题。

**Comment by cnwhy** [comment]
好像规则关没有明确整个万级别都为0的情况，这个零是我按个人习惯加的。
`一亿一千` 和 `一亿零一千`  应该都是符合，只是后一种比较符合我的个人习惯。

**Comment by petesun** [comment]
嗯，理解。
肯定是都符合规范的，只是说，更统一呢，是否更好的问题。
所以，我本来没打算提这个问题。

但是，有一点值得注意，GitHub上有一些实现是不写零的。
税务发票这边，UKey是我做的，不写零。
明年推出的在线网页版，也是做成不写零的。

作者是否考虑，加个参数？^_^
只是建议，哈。

**Comment by petesun** [comment]
作者刚刚的回复，有错字，“关没有”。
难道作者用五笔，惊了，佩服！
我对作者的佩服，犹如滔滔江水连绵不绝。

**Comment by cnwhy** [comment]
后期是 可以加一个 `零都读` 和 `按需读` 的配置
但是 `按需读` 我倾向于 这位对中间插零的解释。
https://www.zhihu.com/question/22629654/answer/54295979

**Comment by petesun** [comment]
嗯，厉害了。
知乎链接，已点关注。
