### ISSUE TITLE
从webpack3升级为webpack4后报错

### ISSUE THREAD

**Issue by xiaohezi205** [cnwhy/nzh#29]
version：1.0.4
![1661768278968](https://user-images.githubusercontent.com/84753977/187179562-7bfa01c7-2897-48e4-86c0-88006c6bd261.png)
![1661768298474](https://user-images.githubusercontent.com/84753977/187179620-a3942d3d-f378-4ed5-9c2d-135bb530d7fd.png)
  代码如下：
let cn =  require( '@/utils/nzh/nzh' )
        (data.mu !== "0") && arr.unshift( cn.Nzh.cn.encodeS(data.mu )+'目');
        (data.xiang !== "0") && arr.unshift( '第'+cn.Nzh.cn.encodeS( data.xiang )+'项');
        (data.kuan !== "0") && arr.unshift( '第'+cn.Nzh.cn.encodeS( data.kuan )+'款');

**Comment by cnwhy** [comment]
引用方式有些奇怪，直接 `npm install nzh` 来使用就好了， 为何要用dist下的文件？
这个报错没猜错的话，因该是启用了js严格模式导致的, 和webpack无关

**Comment by xiaohezi205** [comment]
非常感谢您回复，确实和webpack无关，已经解决了，采用npm install nzh即可，再次感谢！



何昌涛
北京北大英华科技有限公司     项目研发部
https://www.pkulaw.com/ 
Tel：15810951990 / 010-82668266-232
***@***.***
北京市海淀区中关村大街27号中关村大厦9层

 
发件人： why
发送时间： 2022-09-05 10:37
收件人： cnwhy/nzh
抄送： xiaohezi205; Author
主题： Re: [cnwhy/nzh] 从webpack3升级为webpack4后报错 (Issue #29)
引用方式有些奇怪，直接 npm install nzh 来使用就好了， 为何要用dist下的文件？
这个报错没猜错的话，因该是启用了js严格模式导致的, 和webpack无关

**Comment by xiaohezi205** [comment]
非常感谢您回复，确实和webpack无关，已经解决了，采用npm install nzh即可，再次感谢！

> 引用方式有些东西，直接来使用就好了，为什么要用这个`npm install nzh`dist下的文件 报错没猜错的话，该是启用了js严格模式导致的，和webpack相关的
