### ISSUE TITLE
toMoney方法，转0.3时希望是‘零元叁角’，目前是‘叁角’

### ISSUE THREAD

**Issue by fallenaAngel** [cnwhy/nzh#33]
toMoney方法，转-0.3时是‘（负数）零元叁角’，转0.3时希望是‘零元叁角’，目前是‘叁角’，所以不统一，负数时带零，正数时也带一下零

**Comment by cnwhy** [comment]
确实有不一至的问题，现已修复；
增加了加了一个 `unOmitYuan` 配置项，用于控制个位为0时，元的输出；

**Comment by fallenaAngel** [comment]
提示No matching version found for nzh@1.0.9
