### ISSUE TITLE
最新版本1.0.10 cn.js 引入bug

### ISSUE THREAD

**Issue by yujian-123** [cnwhy/nzh#37]
Module not found: Error: Package path ./cn is not exported from package

**Comment by Lucien-X** [comment]
> Module not found: Error: Package path ./cn is not exported from package

我遇到了一样的问题，

Package subbath './cn' is not defined by "exports" in  /node_modules/nzh/package.json

是 Node 应用中引入的，直接导致runtime报错应用启动不了，我先锁 1.0.9 版本解决了
