### ISSUE TITLE
nzhcn.encodeB 传入字符串以 '.' 或 '.000' 结尾会有问题

### ISSUE THREAD

**Issue by hanai** [cnwhy/nzh#4]
如 `14.` 会变成 `14.`，`14.00` 会变成 `壹拾肆`，并没有把点号或零体现出来

**Comment by cnwhy** [comment]
确实不会处理 `14.` 这样的字符串,但我不认为有什么问题,你的应用场景是怎么样的?


至于`14.00` 这个在数学意义上来说是保留两位有效数字,但是如果转为中文,保留零零反倒是怪怪的,
这种情况我只对转金额的时候做了一点处理,比如： 
`14` 会转成 `人民币壹拾肆元整`  
`14.00` 会转成 `人民币壹拾肆元`  
在转金额时`整`字稍稍体现了有效数字的概念,我记得当时老师是这么教的,如果不对,还请指正

**Comment by hanai** [comment]
我是在做一个自定义的数字键盘，在键盘上点击输入，上面会显示当前输入的内容以及中文数字，如果输入点的话原来的中文就变成数字了。

**Comment by cnwhy** [comment]
这样的话,可能需要你先对传入的参数做一次处理, 我这边是不会主动处理非标准数字字符串的.
