### ISSUE TITLE
依赖包拉取不到

### ISSUE THREAD

**Issue by John-xiao** [cnwhy/nzh#40]
是否可以删除依赖"gulp-mocha-phantomjs": "^0.12.1",

因为github访问受限，依赖包拉取不到。。。

14:12:30 PhantomJS not found on PATH
14:12:30 Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
14:12:30 Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
14:12:30 Receiving...

**Comment by kevin100702** [comment]
这个问题在使用自动构建的时候严重的拖慢的构建的速度

**Comment by cnwhy** [comment]
nzh 并没有任何依赖，gulp-mocha-phantomjs 只是开发模式的依赖，正常用`npm` `cnpm` `yarn` 安装 是会安装其他依赖的

**Comment by kevin100702** [comment]
在直接使用npm install时会进行安装， 是否可以把这些 包放到  optionalDependencies 节点，这样安装时可以使用npm install --no-optional 来避免安装到这些包

**Comment by wingkung** [comment]
试试 npm i --production

**Comment by xiaoshu-lin** [comment]
我也遇到这问题了，加--production,--only=prod标志都没用，怎么样都会触发PhantomJS安装

**Comment by xiaoshu-lin** [comment]
> nzh 并没有任何依赖，gulp-mocha-phantomjs 只是开发模式的依赖，正常用`npm` `cnpm` `yarn` 安装 是不会安装其他依赖的

你用了npm-shrinkwrap，dependencies里面加了gulp-mocha-phantomjs
