### ISSUE TITLE
识别“六千八”出错

### ISSUE THREAD

**Issue by iloahz** [cnwhy/nzh#5]
```
> Nzh.cn.decodeS('六千八');
'6008'
```

**Comment by iloahz** [comment]
麻烦看一下吧，多谢

**Comment by cnwhy** [comment]
是这样的，`decode` 函数是能过配制的参数来返向转换的，只是一个配套功能，不太好做过多的兼容
如果你就要是转中文数字，你应该找一些转门做转中文转数字的类，‘1.2万’  ‘3万8‘ 这些都可以正确识别的
